### ISSUE TITLE
Building in iOS 11

### ISSUE THREAD

**Issue by technicallyerik** [mfessenden/SKTiled#13]
To get this to build in iOS 11, I had to remove the zlib module included in the repository and add 				OTHER_LDFLAGS = "-lz"; to the project.

**Comment by mfessenden** [comment]
Thanks! 

I'm currently putting together an update, I'll likely be adding a branch for Xcode 9/Swift 4 with it.

**Comment by technicallyerik** [comment]
Looks like this was addressed in 4444fc5
