### ISSUE TITLE
cocoapods installation error

### ISSUE THREAD

**Issue by retrokid** [mfessenden/SKTiled#14]
Hey,

When i try to install 1.12 version i get this error :

```
[!] Unable to satisfy the following requirements:

- `SKTiled (~> 1.12)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SKTiled (~> 1.12)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

I searched at cocoapods.org and the version number was 1.07 
![screen shot 2017-07-21 at 2 44 37 pm](https://user-images.githubusercontent.com/8542207/28462285-397daf92-6e23-11e7-8920-cd95da5ad3e8.png)

When i change my podfile to SKTiled (~> 1.07) it works.

**Comment by mfessenden** [comment]
Looks like I need to update the podspec for the last release. I'm traveling without my laptop until the 29th, so in the meantime you can build the latest release with Carthage, or just compile & link the frameworks manually.

**Comment by retrokid** [comment]
thank you

**Comment by mfessenden** [comment]
The CocoaPods registry is updated, let me know if you have any problems with it:

[SKTiled v1.12](https://cocoapods.org/pods/SKTiled)
