### ISSUE TITLE
Why Requirements iOS10+?

### ISSUE THREAD

**Issue by zhengying** [mfessenden/SKTiled#2]
Why Requirements iOS10+?
It seem work fine in iOS9+ .

**Comment by mfessenden** [comment]
I've got a GameplayKit update in testing right now that requires features new to iOS10 (pathfinding graphs based on Tiled attributes).

Maintaining both Swift 2.3 & 3.0 branches was difficult so I didn't want to support two different iOS10 versions, but if you or anyone needs to stay on iOS9, I can certainly look into it.

**Comment by zhengying** [comment]
Thanks for your hard work!
Very nice project.
Long-term considerations, I agree that you only support iOS10+

but now IOS 9 occupancy rate 30%（Not a small number）you can write a guide for iOS9 , it will be more project use this nice project now. 

![screen shot 2016-12-09 at 10 03 36 am](https://cloud.githubusercontent.com/assets/1042545/21034796/6dfd8be0-bdf5-11e6-9964-842b534f1165.png)

**Comment by mfessenden** [comment]
The next release will either be deployable on iOS9 & iOS10 or reside in a separate branch. Thanks for bringing this to my attention!
