### ISSUE TITLE
Error thrown on new xcode10 swift 4.2

### ISSUE THREAD

**Issue by pxlRider** [mfessenden/SKTiled#20]
On line 840 inside SKTilemapParser I get:

Thread 1: signal SIGABRT
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

**Comment by mfessenden** [comment]
This is fixed with the latest release and Xcode 10.1/Swift 4.2. If you have any more problems, feel free to open a new issue.
