### ISSUE TITLE
addTileAt not replacing tile properly

### ISSUE THREAD

**Issue by andrewpeng02** [mfessenden/SKTiled#31]
Hi, first of all thank you for the amazing framework! It's really hard to find stuff on tile maps in swift, so this framework really helps. 

I'm trying to use `layer.addTileAt` to change a tile at a coordinate, but I'm running into an issue. Calling that function removes the tile, but it doesn't replace the tile with a new one. For example, downloading your repo and adding this line of code on line 450 of SKTiled/Demo/SKTiledDemoScene.swift after `updatePropertiesInfo()`:

`let newTile = (tilemap.getLayers(named: "Ground")[0] as? SKTileLayer)?.addTileAt(coord: coord, gid: 41)`

Should change the tile to a new tile with gid 41 (I think this corresponds to a wall tile?) but it only removes and doesn't replace the tile. I tested this on the isometric (second) map. It seems to return the proper wall tile but it isn't visible, but I couldn't figure out how to fix this issue.

Any help would be greatly appreciated!

**Comment by mfessenden** [comment]
This looks like a bug updating the tile objects.

Try adding a second line to the demo scene file:

```swift
newTile?.draw()
```

Does that fix it for you?

**Comment by andrewpeng02** [comment]
That works, thank you!
