### ISSUE TITLE
Loading new tilemap memory leak

### ISSUE THREAD

**Issue by andrewpeng02** [mfessenden/SKTiled#32]
Whenever I try to leave my class that inherits SKTiledScene using view.presentScene() and then display the tile map again, memory isn't released when it should be. A simple example is using your demo iOS project: switching between the various tilemaps increases the memory even when I go back to the first one, which will eventually result in a crash. I'm suspecting that there's a strong reference cycle in SKTiledScene that's stopping the tilemap from being deallocated, but I can't find it myself. Any help would be greatly appreciated!

![Screen Shot 2020-12-09 at 10 39 55 AM](https://user-images.githubusercontent.com/47485510/101662801-9134a900-3a0f-11eb-9909-f95000b8af9c.png)

**Comment by mfessenden** [comment]
Yep, that's a long-standing bug. 

In the `SKTiledSceneDelegate` protocol, the tilemap & camera node properties should be optionals, not implicitly unwrapped optionals. It's been fixed, but given that it's fundamentally changing the scene delegate protocol, I've pushed it off until the next point release (1.3).

```swift

// API version 1.2
if let tiledScene = (self.view as? SKView)?.scene as? SKTiledSceneDelegate {
    let renderSize = tiledScene.tilemap.sizeInPoints
    let world = tiledScene.cameraNode.world
}

// API version 1.3
if let tiledScene = (self.view as? SKView)?.scene as? TiledSceneDelegate {
    let renderSize = tiledScene.tilemap?.sizeInPoints
    let world = tiledScene.cameraNode?.world
}
```

I'm still working on the next release, but if it's crashing your app, I could possibly push up a development branch.

**Comment by andrewpeng02** [comment]
Pushing the changes to a dev branch would be greatly appreciated :) Thanks

**Comment by andrewpeng02** [comment]
Hey, I just wanted to check-in with you to see if you can push up a dev branch anytime soon. This bug is indeed breaking our app, so it would be nice to hear from you- thanks!

**Comment by mfessenden** [comment]
I've got some free time now that the holidays here are over, so I'll plan on pushing something up this week.

**Comment by mfessenden** [comment]
I've uploaded a new branch [**release/1.30**][branch-13-url].

I've done a lot of cleanup of the API for this release; I'm still writing a migration guide, but check out the [**What's New**][whats-new-url] documentation page for details.

I've had a bit of trouble building the framework with the Xcode 12.3 releases & Carthage in my test projects... apparently 12.3 has a number of bugs so until I can look into it more, I'd recommend using 12.2 if you run into problems.


[branch-13-url]:https://github.com/mfessenden/SKTiled/tree/release/1.30
[whats-new-url]:https://mfessenden.github.io/SKTiled/1.3/whats-new.html#api-changes

**Comment by andrewpeng02** [comment]
Looks like the memory leak was fixed, thank you!

**Comment by andrewpeng02** [comment]
Sorry, I just wanted to know how you fixed the strong reference cycle to remove the memory leak since I spent some time myself trying to fix it but to no avail.

**Comment by mfessenden** [comment]
The `SKTiledSceneDelegate` protocol & `SKTiledSceneCamera` nodes held strong references to the following nodes:

- `SKTiledSceneDelegate.tilemap`
- `SKTiledSceneDelegate.cameraNode` 
- `SKTiledSceneCamera.world`

I had read that the the `SKView.presentScene` method would properly deallocate the current scene and its children, but that wasn't the case so each scene and its children would remain in memory.
