### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [mfessenden/SKTiled#4]
Hi,
For iOS and macOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://goo.gl/8AMTfw)
- [Carthage Tutorial: Getting Started](https://goo.gl/9pVzFX)
- [Making Carthage-compatible Frameworks with Swift](https://goo.gl/SzPe8j)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods](https://goo.gl/mzZ3Si) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by mfessenden** [comment]
Thanks for the links! 

Cocoapods support will be added version soon, probably in the next release. I'm looking into Carthage as well. 

Currently compiling the project builds a demo app for either iOS or macOS, so I'm adding targets to the project to build frameworks for each OS... so once all of that is working, I'll push it to the current master and see if it works.

**Comment by mfessenden** [comment]
Updated the latest release (1.07) to build with both Carthage & CocoaPods, so I'm going to close this now.
