### ISSUE TITLE
NSArray was mutated while being enumerated

### ISSUE THREAD

**Issue by aornano** [mfessenden/SKTiled#5]
Hello Michael, seems that sometimes the actual framework (v.1.07) crash with the message on subject. The crash is stopped to appDelegate so there isn't a specific line of code, but during my analisys to the debug error output, I've discovered the array `layers` is involved when the tileLayers are in paused mode. So I've change this code:

**SKTiledMap.swift** (original)

```
/// Pauses the node, and colors all of its children darker.
    override open var isPaused: Bool {
        didSet {
            guard oldValue != isPaused else { return }
            let newColor: SKColor = isPaused ? SKColor(white: 0, alpha: 0.25) : SKColor.clear
            let newColorBlendFactor: CGFloat = isPaused ? 0.2 : 0.0
            
            speed = isPaused ? 0 : 1.0
            color = newColor
            
            layers.forEach { layer in
                layer.color = newColor
                layer.colorBlendFactor = newColorBlendFactor
                layer.isPaused = isPaused
                //layer.speed = speed
            }
        }
    }
```

with this code:

```
 /// pauses the node, and colors all of its children darker.
    override open var isPaused: Bool {
        didSet {
            guard oldValue != isPaused else { return }
            let newColor: SKColor = isPaused ? SKColor(white: 0, alpha: 0.25) : SKColor.clear
            let newColorBlendFactor: CGFloat = isPaused ? 0.2 : 0.0
            
            speed = isPaused ? 0 : 1.0
            color = newColor
            let tempLayers:Set<TiledLayerObject> = layers
            tempLayers.forEach { layer in
                layer.color = newColor
                layer.colorBlendFactor = newColorBlendFactor
                layer.isPaused = isPaused
                //layer.speed = speed
            }
            layers = tempLayers
        }
    }
```
where I've found a workaround ,I've created a temporary array to avoid enumeration to the original..

I've found also this file:

**SKTileLayer.swift**

```
override open var isPaused: Bool {
        didSet {
            tiles.forEach { tile in
                tile?.color = self.color
                tile?.colorBlendFactor = self.colorBlendFactor
            }
        }
    }
```

where I've maded:

```
override open var isPaused: Bool {
        didSet {
            let tempTiles:TilesArray = tiles
            tempTiles.forEach { tile in
                tile?.color = self.color
                tile?.colorBlendFactor = self.colorBlendFactor
            }
            tiles = tempTiles
        }
    }
```

**Comment by mfessenden** [comment]
Nice catch! 

Looks like you can trigger a crash if the tile layer is being rendered and the app is paused. I'll make sure add this into the next release.

**Comment by aornano** [comment]
Thank you, after my changes and after thousand of tries all crash are disappeared then seems work well.

**Comment by aornano** [comment]
Hello man, with the new 10.2 iOS release the problem still appeared only for **SKTileLayer** so I've change the code with:

> override open var isPaused: Bool {
>         didSet {
>             let tempTiles:TilesArray = tiles
>             for tile in tempTiles {
>                 if let t = tile {
>                     t.color = self.color
>                     t.colorBlendFactor = self.colorBlendFactor
>                 }
>             }
>             tiles = tempTiles
>         }
>     }

Seems that, sometime the foreach don't consider that a tile could be nil, I hope that my last change correct this issue. For now seems all work well. Let me know if you have a better idea.

**Comment by mfessenden** [comment]
Unfortunately that fix doesn't work for me if the device is paused before all of the tiles are finished rendering with some maps. I'm currently working with a fix, so I hope to have that up this week.

In early versions of this framework, everything was rendered on the main thread. In iOS that meant that  larger maps would lock the device up for upwards of 5 seconds or more, so I added a render queue to the XML parser so that rendering could take place on a high priority thread while the interface remains responsive. 

The issue is that tiles can't be added to the scene while paused, resulting in a crash. I've reworked the rendering code moving the render queue to the `SKTilemap` node itself, so that we can do a check on the state of rendering before allowing the node to be paused. I'm testing it now, so with any luck it'll be up this week. 👍

**Comment by aornano** [comment]
During more deepest analisys, I've found the method where we have this crash:

`fileprivate func buildTileAt(coord: CGPoint, id: UInt32) -> SKTile? { ... }`

I've tried NSLock() instruction (lock() and unlock()) to preserve changes only during the method execution but this instructions delayed too much the rendering on the main thread..
Now I don't find another solution, let me know if you have other ideas..

**Comment by mfessenden** [comment]
I've just pushed the changes I mentioned before; the rendering of the tiles is done on a queue parented to the `SKTilemap` itself. If the scene is paused, the tilemap will sync current rendering operations before pausing. 

I've been testing this solution and haven't gotten any crashes with my test files, so hopefully we're in the clear.

**Comment by aornano** [comment]
Yeah, me too. Now works perfect. Thank you Michael, this is a great correction.
